### ISSUE TITLE
Where is "outputs_main.csv" file?

### ISSUE THREAD

**Issue by tiensu** [shivam-199/Python-Emotion-using-EEG-Signal#1]
Hi you,
I didn't see where "outputs_main.csv" file was created, but it was used in your code. Please tell me how to create that file?
Thank you very much!

**Comment by VinayFaria** [comment]
@shivam-199 has provided it here "https://github.com/shivam-199/Python-Emotion-using-EEG-Signal/blob/master/outputs_main.csv" i.e. on home page.

**Comment by vsvn-SuNT** [comment]
Thank you, @VinayFaria and @shivam-199 !
